
title: Minuet80
description: ‘나는 운을 믿는다’ 그리고 더 열심히 일할수록 더 많은 운이 따르곤 했다.
url: https://minuet80.github.io/
permalink: ':title/'

markdown: kramdown
baseurl: ""
full-version: "http://webjeda.com/karna-full/"

sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: minuet80-github-io

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 1.0

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag